create table if not exists public.influencer_creator_suggestions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  suggestion_text text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint influencer_creator_suggestions_text_length check (char_length(trim(suggestion_text)) between 3 and 2000),
  constraint influencer_creator_suggestions_status_valid check (status in ('pending', 'reviewed', 'accepted', 'rejected'))
);

create index if not exists influencer_creator_suggestions_user_idx
  on public.influencer_creator_suggestions (user_id, created_at desc);

create index if not exists influencer_creator_suggestions_status_idx
  on public.influencer_creator_suggestions (status, created_at desc);

alter table public.influencer_creator_suggestions enable row level security;

drop policy if exists "influencer_creator_suggestions_select_own" on public.influencer_creator_suggestions;
create policy "influencer_creator_suggestions_select_own"
on public.influencer_creator_suggestions
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "influencer_creator_suggestions_insert_own" on public.influencer_creator_suggestions;
create policy "influencer_creator_suggestions_insert_own"
on public.influencer_creator_suggestions
for insert
to authenticated
with check (auth.uid() = user_id);

