create table if not exists public.influencer_votes (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  nominee_id bigint not null references public.influencer_next_month_nominees(id) on delete cascade,
  nomination_month date not null,
  created_at timestamptz not null default now(),
  constraint influencer_votes_unique_user_cycle unique (user_id, nomination_month)
);

create index if not exists influencer_votes_user_cycle_idx
  on public.influencer_votes (user_id, nomination_month);

create index if not exists influencer_votes_nominee_idx
  on public.influencer_votes (nominee_id);

alter table public.influencer_votes enable row level security;

drop policy if exists "influencer_votes_select_own" on public.influencer_votes;
create policy "influencer_votes_select_own"
on public.influencer_votes
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "influencer_votes_insert_own" on public.influencer_votes;
create policy "influencer_votes_insert_own"
on public.influencer_votes
for insert
to authenticated
with check (auth.uid() = user_id);

