create table if not exists public.plant_timeline_updates (
  id bigint generated by default as identity primary key,
  plant_id bigint not null references public.plants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  photos jsonb not null default '[]'::jsonb,
  note text not null default '',
  observed_on date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists plant_timeline_updates_plant_id_idx on public.plant_timeline_updates (plant_id);
create index if not exists plant_timeline_updates_user_id_idx on public.plant_timeline_updates (user_id);
create index if not exists plant_timeline_updates_observed_on_idx on public.plant_timeline_updates (observed_on desc);

alter table public.plant_timeline_updates enable row level security;

drop policy if exists "plant_timeline_updates_select_authenticated" on public.plant_timeline_updates;
create policy "plant_timeline_updates_select_authenticated"
on public.plant_timeline_updates
for select
to authenticated
using (true);

drop policy if exists "plant_timeline_updates_insert_own" on public.plant_timeline_updates;
create policy "plant_timeline_updates_insert_own"
on public.plant_timeline_updates
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "plant_timeline_updates_update_own" on public.plant_timeline_updates;
create policy "plant_timeline_updates_update_own"
on public.plant_timeline_updates
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "plant_timeline_updates_delete_own" on public.plant_timeline_updates;
create policy "plant_timeline_updates_delete_own"
on public.plant_timeline_updates
for delete
to authenticated
using (auth.uid() = user_id);
