create table if not exists public.growmate_log_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.growmate_log_types (name, sort_order, is_active)
values
  ('General', 10, true),
  ('Care Plan', 20, true)
on conflict (name) do update
set
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;

alter table public.growmate_logs
  add column if not exists conversation_id bigint references public.growmate_conversations(id) on delete set null,
  add column if not exists log_type_id bigint references public.growmate_log_types(id) on delete set null;

update public.growmate_logs l
set log_type_id = t.id
from public.growmate_log_types t
where t.name = 'Care Plan'
  and l.log_type_id is null;

create index if not exists growmate_logs_conversation_id_idx on public.growmate_logs (conversation_id);
create index if not exists growmate_logs_log_type_id_idx on public.growmate_logs (log_type_id);
