create table if not exists public.growmate_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  plant_id bigint references public.plants(id) on delete set null,
  title text not null,
  topic text not null default 'Care Plan',
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists growmate_logs_user_id_created_at_idx on public.growmate_logs (user_id, created_at desc);

alter table public.growmate_logs enable row level security;

drop policy if exists "growmate_logs_select_own" on public.growmate_logs;
create policy "growmate_logs_select_own"
on public.growmate_logs
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "growmate_logs_insert_own" on public.growmate_logs;
create policy "growmate_logs_insert_own"
on public.growmate_logs
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "growmate_logs_update_own" on public.growmate_logs;
create policy "growmate_logs_update_own"
on public.growmate_logs
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "growmate_logs_delete_own" on public.growmate_logs;
create policy "growmate_logs_delete_own"
on public.growmate_logs
for delete
to authenticated
using (auth.uid() = user_id);
