create table if not exists public.growmate_topics (
  id bigint generated by default as identity primary key,
  label text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists growmate_topics_label_unique_idx on public.growmate_topics (label);
create index if not exists growmate_topics_active_sort_idx on public.growmate_topics (is_active, sort_order asc);

alter table public.growmate_topics enable row level security;

drop policy if exists "growmate_topics_select_all_authenticated" on public.growmate_topics;
create policy "growmate_topics_select_all_authenticated"
on public.growmate_topics
for select
to authenticated
using (is_active = true);

insert into public.growmate_topics (label, sort_order, is_active)
values
  ('My plant looks sick', 10, true),
  ('Help me propagate', 20, true),
  ('Design my garden', 30, true),
  ('Moon phase gardening', 40, true),
  ('Best indoor plants', 50, true),
  ('Preserving vegetables', 60, true)
on conflict (label) do update
set
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();
