create table if not exists public.influencer_profiles (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  short_description text not null default '',
  description text not null default '',
  avatar_url text,
  influencer_of_the_month boolean not null default false,
  featured_month date,
  votes_count integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint influencer_profiles_votes_nonnegative check (votes_count >= 0),
  constraint influencer_profiles_featured_month_required check (
    (influencer_of_the_month = false)
    or (featured_month is not null)
  )
);

create table if not exists public.influencer_videos (
  id bigint generated by default as identity primary key,
  influencer_profile_id bigint not null references public.influencer_profiles(id) on delete cascade,
  title text not null,
  video_url text,
  thumbnail_url text,
  duration_seconds integer not null default 0,
  views_count integer not null default 0,
  published_at timestamptz,
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint influencer_videos_duration_nonnegative check (duration_seconds >= 0),
  constraint influencer_videos_views_nonnegative check (views_count >= 0)
);

create index if not exists influencer_profiles_featured_idx
  on public.influencer_profiles (influencer_of_the_month, featured_month desc);

create index if not exists influencer_profiles_published_idx
  on public.influencer_profiles (is_published, created_at desc);

create index if not exists influencer_videos_profile_idx
  on public.influencer_videos (influencer_profile_id, sort_order asc, created_at desc);

create index if not exists influencer_videos_published_idx
  on public.influencer_videos (is_published, published_at desc);

alter table public.influencer_profiles enable row level security;
alter table public.influencer_videos enable row level security;

drop policy if exists "influencer_profiles_select_published_authenticated" on public.influencer_profiles;
create policy "influencer_profiles_select_published_authenticated"
on public.influencer_profiles
for select
to authenticated
using (is_published = true);

drop policy if exists "influencer_profiles_insert_authenticated" on public.influencer_profiles;
create policy "influencer_profiles_insert_authenticated"
on public.influencer_profiles
for insert
to authenticated
with check (true);

drop policy if exists "influencer_profiles_update_authenticated" on public.influencer_profiles;
create policy "influencer_profiles_update_authenticated"
on public.influencer_profiles
for update
to authenticated
using (true)
with check (true);

drop policy if exists "influencer_profiles_delete_authenticated" on public.influencer_profiles;
create policy "influencer_profiles_delete_authenticated"
on public.influencer_profiles
for delete
to authenticated
using (true);

drop policy if exists "influencer_videos_select_published_authenticated" on public.influencer_videos;
create policy "influencer_videos_select_published_authenticated"
on public.influencer_videos
for select
to authenticated
using (is_published = true);

drop policy if exists "influencer_videos_insert_authenticated" on public.influencer_videos;
create policy "influencer_videos_insert_authenticated"
on public.influencer_videos
for insert
to authenticated
with check (true);

drop policy if exists "influencer_videos_update_authenticated" on public.influencer_videos;
create policy "influencer_videos_update_authenticated"
on public.influencer_videos
for update
to authenticated
using (true)
with check (true);

drop policy if exists "influencer_videos_delete_authenticated" on public.influencer_videos;
create policy "influencer_videos_delete_authenticated"
on public.influencer_videos
for delete
to authenticated
using (true);

