create table if not exists public.quick_actions (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  icon_key text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists quick_actions_title_unique_idx on public.quick_actions (title);
create index if not exists quick_actions_active_sort_idx on public.quick_actions (is_active, sort_order asc);

alter table public.quick_actions enable row level security;

drop policy if exists "quick_actions_select_all_authenticated" on public.quick_actions;
create policy "quick_actions_select_all_authenticated"
on public.quick_actions
for select
to authenticated
using (is_active = true);

insert into public.quick_actions (title, description, icon_key, sort_order, is_active)
values
  ('Indoor Plant Recommendations', 'Get indoor plant suggestions based on your space and preferences.', 'flower', 10, true),
  ('Pest & Disease Diagnosis', 'Describe symptoms to identify and treat common plant pests and diseases.', 'bug', 20, true),
  ('Soil & Fertilizer Guide', 'Find the best soil mix and fertilizer for your plants.', 'bean', 30, true),
  ('Watering Schedule Creator', 'Create a watering schedule tailored to your plant and environment.', 'droplets', 40, true),
  ('Plant Companion Finder', 'Discover plants that grow well together and support healthy growth.', 'users', 50, true),
  ('DIY Project Ideas', 'Explore creative and practical DIY gardening projects.', 'hammer', 60, true),
  ('Gardening for Beginners', 'Learn the basics with simple, step-by-step gardening guidance.', 'graduation', 70, true),
  ('Advanced Gardener''s Hub', 'Dive into advanced topics like grafting, breeding, and hydroponics.', 'flask', 80, true),
  ('Sustainable Gardening', 'Learn eco-friendly practices that support soil, water, and wildlife.', 'recycle', 90, true)
on conflict (title) do update
set
  description = excluded.description,
  icon_key = excluded.icon_key,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();
