create table if not exists public.past_spotlight_creators (
  id bigint generated by default as identity primary key,
  influencer_profile_id bigint not null references public.influencer_profiles(id) on delete cascade,
  spotlight_month date not null,
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint past_spotlight_creators_sort_nonnegative check (sort_order >= 0),
  constraint past_spotlight_creators_unique_profile_month unique (influencer_profile_id, spotlight_month)
);

create index if not exists past_spotlight_creators_month_idx
  on public.past_spotlight_creators (spotlight_month desc, sort_order asc, created_at desc);

create index if not exists past_spotlight_creators_published_idx
  on public.past_spotlight_creators (is_published, spotlight_month desc);

create index if not exists past_spotlight_creators_profile_idx
  on public.past_spotlight_creators (influencer_profile_id);

alter table public.past_spotlight_creators enable row level security;

drop policy if exists "past_spotlight_creators_select_published_public" on public.past_spotlight_creators;
create policy "past_spotlight_creators_select_published_public"
on public.past_spotlight_creators
for select
to anon, authenticated
using (is_published = true);

drop policy if exists "past_spotlight_creators_insert_authenticated" on public.past_spotlight_creators;
create policy "past_spotlight_creators_insert_authenticated"
on public.past_spotlight_creators
for insert
to authenticated
with check (true);

drop policy if exists "past_spotlight_creators_update_authenticated" on public.past_spotlight_creators;
create policy "past_spotlight_creators_update_authenticated"
on public.past_spotlight_creators
for update
to authenticated
using (true)
with check (true);

drop policy if exists "past_spotlight_creators_delete_authenticated" on public.past_spotlight_creators;
create policy "past_spotlight_creators_delete_authenticated"
on public.past_spotlight_creators
for delete
to authenticated
using (true);

