create table if not exists public.growmate_conversations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  plant_id bigint references public.plants(id) on delete set null,
  title text not null default 'New conversation',
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.growmate_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.growmate_conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists growmate_conversations_user_id_updated_at_idx on public.growmate_conversations (user_id, updated_at desc);
create index if not exists growmate_messages_conversation_id_created_at_idx on public.growmate_messages (conversation_id, created_at asc);

alter table public.growmate_conversations enable row level security;
alter table public.growmate_messages enable row level security;

drop policy if exists "growmate_conversations_select_own" on public.growmate_conversations;
create policy "growmate_conversations_select_own"
on public.growmate_conversations
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "growmate_conversations_insert_own" on public.growmate_conversations;
create policy "growmate_conversations_insert_own"
on public.growmate_conversations
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "growmate_conversations_update_own" on public.growmate_conversations;
create policy "growmate_conversations_update_own"
on public.growmate_conversations
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "growmate_conversations_delete_own" on public.growmate_conversations;
create policy "growmate_conversations_delete_own"
on public.growmate_conversations
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "growmate_messages_select_own" on public.growmate_messages;
create policy "growmate_messages_select_own"
on public.growmate_messages
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "growmate_messages_insert_own" on public.growmate_messages;
create policy "growmate_messages_insert_own"
on public.growmate_messages
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "growmate_messages_update_own" on public.growmate_messages;
create policy "growmate_messages_update_own"
on public.growmate_messages
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "growmate_messages_delete_own" on public.growmate_messages;
create policy "growmate_messages_delete_own"
on public.growmate_messages
for delete
to authenticated
using (auth.uid() = user_id);
