create table if not exists public.garden_gallery_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists garden_gallery_entries_user_id_idx on public.garden_gallery_entries (user_id);
create index if not exists garden_gallery_entries_created_at_idx on public.garden_gallery_entries (created_at desc);

create table if not exists public.garden_gallery_photos (
  id bigint generated by default as identity primary key,
  entry_id bigint not null references public.garden_gallery_entries(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  photo_url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists garden_gallery_photos_entry_id_idx on public.garden_gallery_photos (entry_id);
create index if not exists garden_gallery_photos_user_id_idx on public.garden_gallery_photos (user_id);

create table if not exists public.garden_gallery_entry_plants (
  id bigint generated by default as identity primary key,
  entry_id bigint not null references public.garden_gallery_entries(id) on delete cascade,
  plant_id bigint not null references public.plants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint garden_gallery_entry_plants_unique unique (entry_id, plant_id)
);

create index if not exists garden_gallery_entry_plants_entry_id_idx on public.garden_gallery_entry_plants (entry_id);
create index if not exists garden_gallery_entry_plants_plant_id_idx on public.garden_gallery_entry_plants (plant_id);
create index if not exists garden_gallery_entry_plants_user_id_idx on public.garden_gallery_entry_plants (user_id);

alter table public.garden_gallery_entries enable row level security;
alter table public.garden_gallery_photos enable row level security;
alter table public.garden_gallery_entry_plants enable row level security;

drop policy if exists "garden_gallery_entries_select_authenticated" on public.garden_gallery_entries;
create policy "garden_gallery_entries_select_authenticated"
on public.garden_gallery_entries
for select
to authenticated
using (true);

drop policy if exists "garden_gallery_entries_insert_own" on public.garden_gallery_entries;
create policy "garden_gallery_entries_insert_own"
on public.garden_gallery_entries
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "garden_gallery_entries_update_own" on public.garden_gallery_entries;
create policy "garden_gallery_entries_update_own"
on public.garden_gallery_entries
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "garden_gallery_entries_delete_own" on public.garden_gallery_entries;
create policy "garden_gallery_entries_delete_own"
on public.garden_gallery_entries
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "garden_gallery_photos_select_authenticated" on public.garden_gallery_photos;
create policy "garden_gallery_photos_select_authenticated"
on public.garden_gallery_photos
for select
to authenticated
using (true);

drop policy if exists "garden_gallery_photos_insert_own" on public.garden_gallery_photos;
create policy "garden_gallery_photos_insert_own"
on public.garden_gallery_photos
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "garden_gallery_photos_update_own" on public.garden_gallery_photos;
create policy "garden_gallery_photos_update_own"
on public.garden_gallery_photos
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "garden_gallery_photos_delete_own" on public.garden_gallery_photos;
create policy "garden_gallery_photos_delete_own"
on public.garden_gallery_photos
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "garden_gallery_entry_plants_select_authenticated" on public.garden_gallery_entry_plants;
create policy "garden_gallery_entry_plants_select_authenticated"
on public.garden_gallery_entry_plants
for select
to authenticated
using (true);

drop policy if exists "garden_gallery_entry_plants_insert_own" on public.garden_gallery_entry_plants;
create policy "garden_gallery_entry_plants_insert_own"
on public.garden_gallery_entry_plants
for insert
to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.garden_gallery_entries
    where garden_gallery_entries.id = entry_id
      and garden_gallery_entries.user_id = auth.uid()
  )
  and exists (
    select 1
    from public.plants
    where plants.id = plant_id
      and plants.user_id = auth.uid()
  )
);

drop policy if exists "garden_gallery_entry_plants_update_own" on public.garden_gallery_entry_plants;
create policy "garden_gallery_entry_plants_update_own"
on public.garden_gallery_entry_plants
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "garden_gallery_entry_plants_delete_own" on public.garden_gallery_entry_plants;
create policy "garden_gallery_entry_plants_delete_own"
on public.garden_gallery_entry_plants
for delete
to authenticated
using (auth.uid() = user_id);
