create table if not exists public.influencer_next_month_nominees (
  id bigint generated by default as identity primary key,
  influencer_profile_id bigint not null references public.influencer_profiles(id) on delete cascade,
  nomination_month date not null,
  votes_count integer not null default 0,
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint influencer_next_month_nominees_votes_nonnegative check (votes_count >= 0),
  constraint influencer_next_month_nominees_sort_nonnegative check (sort_order >= 0),
  constraint influencer_next_month_nominees_unique_profile_month unique (influencer_profile_id, nomination_month)
);

create index if not exists influencer_next_month_nominees_month_idx
  on public.influencer_next_month_nominees (nomination_month desc, sort_order asc, created_at desc);

create index if not exists influencer_next_month_nominees_published_idx
  on public.influencer_next_month_nominees (is_published, nomination_month desc);

create index if not exists influencer_next_month_nominees_profile_idx
  on public.influencer_next_month_nominees (influencer_profile_id);

alter table public.influencer_next_month_nominees enable row level security;

drop policy if exists "influencer_next_month_nominees_select_published_public" on public.influencer_next_month_nominees;
create policy "influencer_next_month_nominees_select_published_public"
on public.influencer_next_month_nominees
for select
to anon, authenticated
using (is_published = true);

drop policy if exists "influencer_next_month_nominees_insert_authenticated" on public.influencer_next_month_nominees;
create policy "influencer_next_month_nominees_insert_authenticated"
on public.influencer_next_month_nominees
for insert
to authenticated
with check (true);

drop policy if exists "influencer_next_month_nominees_update_authenticated" on public.influencer_next_month_nominees;
create policy "influencer_next_month_nominees_update_authenticated"
on public.influencer_next_month_nominees
for update
to authenticated
using (true)
with check (true);

drop policy if exists "influencer_next_month_nominees_delete_authenticated" on public.influencer_next_month_nominees;
create policy "influencer_next_month_nominees_delete_authenticated"
on public.influencer_next_month_nominees
for delete
to authenticated
using (true);

