create table if not exists public.post_plants (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  plant_id bigint not null references public.plants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint post_plants_unique_attachment unique (post_id, plant_id)
);

create index if not exists post_plants_post_id_idx on public.post_plants (post_id);
create index if not exists post_plants_plant_id_idx on public.post_plants (plant_id);
create index if not exists post_plants_user_id_idx on public.post_plants (user_id);

alter table public.post_plants enable row level security;

drop policy if exists "post_plants_select_authenticated" on public.post_plants;
create policy "post_plants_select_authenticated"
on public.post_plants
for select
to authenticated
using (true);

drop policy if exists "post_plants_insert_own" on public.post_plants;
create policy "post_plants_insert_own"
on public.post_plants
for insert
to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.posts
    where posts.id = post_id
      and posts.user_id = auth.uid()
  )
  and exists (
    select 1
    from public.plants
    where plants.id = plant_id
      and plants.user_id = auth.uid()
  )
);

drop policy if exists "post_plants_update_own" on public.post_plants;
create policy "post_plants_update_own"
on public.post_plants
for update
to authenticated
using (auth.uid() = user_id)
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.posts
    where posts.id = post_id
      and posts.user_id = auth.uid()
  )
  and exists (
    select 1
    from public.plants
    where plants.id = plant_id
      and plants.user_id = auth.uid()
  )
);

drop policy if exists "post_plants_delete_own" on public.post_plants;
create policy "post_plants_delete_own"
on public.post_plants
for delete
to authenticated
using (auth.uid() = user_id);
