create table if not exists public.plants (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  common_name text not null,
  scientific_name text,
  description text,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists plants_user_id_idx on public.plants (user_id);
create index if not exists plants_created_at_idx on public.plants (created_at desc);

create table if not exists public.plant_photos (
  id bigint generated by default as identity primary key,
  plant_id bigint not null references public.plants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  photo_url text not null,
  sort_order integer not null default 0,
  source text not null default 'camera',
  created_at timestamptz not null default now()
);

create index if not exists plant_photos_plant_id_idx on public.plant_photos (plant_id);
create index if not exists plant_photos_user_id_idx on public.plant_photos (user_id);

create table if not exists public.plant_care_profiles (
  id bigint generated by default as identity primary key,
  plant_id bigint not null unique references public.plants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  light_level text,
  watering_interval_days integer,
  temperature_min_c numeric(5,2),
  temperature_max_c numeric(5,2),
  humidity_percent integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint plant_care_profiles_humidity_range check (humidity_percent is null or (humidity_percent >= 0 and humidity_percent <= 100)),
  constraint plant_care_profiles_watering_interval_nonnegative check (watering_interval_days is null or watering_interval_days >= 0)
);

create index if not exists plant_care_profiles_user_id_idx on public.plant_care_profiles (user_id);

create table if not exists public.plant_care_sections (
  id bigint generated by default as identity primary key,
  plant_id bigint not null references public.plants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  section_key text not null,
  title text not null,
  content text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint plant_care_sections_unique_per_plant unique (plant_id, section_key)
);

create index if not exists plant_care_sections_plant_id_idx on public.plant_care_sections (plant_id);
create index if not exists plant_care_sections_user_id_idx on public.plant_care_sections (user_id);

alter table public.plants enable row level security;
alter table public.plant_photos enable row level security;
alter table public.plant_care_profiles enable row level security;
alter table public.plant_care_sections enable row level security;

-- Plants policies
drop policy if exists "plants_select_authenticated" on public.plants;
create policy "plants_select_authenticated"
on public.plants
for select
to authenticated
using (true);

drop policy if exists "plants_insert_own" on public.plants;
create policy "plants_insert_own"
on public.plants
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "plants_update_own" on public.plants;
create policy "plants_update_own"
on public.plants
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "plants_delete_own" on public.plants;
create policy "plants_delete_own"
on public.plants
for delete
to authenticated
using (auth.uid() = user_id);

-- Plant photos policies
drop policy if exists "plant_photos_select_authenticated" on public.plant_photos;
create policy "plant_photos_select_authenticated"
on public.plant_photos
for select
to authenticated
using (true);

drop policy if exists "plant_photos_insert_own" on public.plant_photos;
create policy "plant_photos_insert_own"
on public.plant_photos
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "plant_photos_update_own" on public.plant_photos;
create policy "plant_photos_update_own"
on public.plant_photos
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "plant_photos_delete_own" on public.plant_photos;
create policy "plant_photos_delete_own"
on public.plant_photos
for delete
to authenticated
using (auth.uid() = user_id);

-- Plant care profiles policies
drop policy if exists "plant_care_profiles_select_authenticated" on public.plant_care_profiles;
create policy "plant_care_profiles_select_authenticated"
on public.plant_care_profiles
for select
to authenticated
using (true);

drop policy if exists "plant_care_profiles_insert_own" on public.plant_care_profiles;
create policy "plant_care_profiles_insert_own"
on public.plant_care_profiles
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "plant_care_profiles_update_own" on public.plant_care_profiles;
create policy "plant_care_profiles_update_own"
on public.plant_care_profiles
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "plant_care_profiles_delete_own" on public.plant_care_profiles;
create policy "plant_care_profiles_delete_own"
on public.plant_care_profiles
for delete
to authenticated
using (auth.uid() = user_id);

-- Plant care sections policies
drop policy if exists "plant_care_sections_select_authenticated" on public.plant_care_sections;
create policy "plant_care_sections_select_authenticated"
on public.plant_care_sections
for select
to authenticated
using (true);

drop policy if exists "plant_care_sections_insert_own" on public.plant_care_sections;
create policy "plant_care_sections_insert_own"
on public.plant_care_sections
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "plant_care_sections_update_own" on public.plant_care_sections;
create policy "plant_care_sections_update_own"
on public.plant_care_sections
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "plant_care_sections_delete_own" on public.plant_care_sections;
create policy "plant_care_sections_delete_own"
on public.plant_care_sections
for delete
to authenticated
using (auth.uid() = user_id);
